language: android
sudo: false

cache:
  directories:
    - $HOME/.m2

before_install:
  - mkdir ~/bin
  - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein -P ~/bin/
  - chmod a+x ~/bin/lein
  - mkdir ~/.lein

android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra-android-m2repository

lein: ~/bin/lein

script:
    - DEBUG=1 lein with-profile travis droid compile
    - DEBUG=1 lein with-profile travis droid create-apk
